//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
		public class AutoAttack
		{
			private double attackTime;
			private double cooldown;
			private List<EffectType> effects;

			public AutoAttack ()
			{
			}
		}
}

