//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public enum CastType //типы абилок по способам применения
		{
		Unknown, //заглушка
		Chanelling, //нужно стоять и кастовать какое-то время
		InstantCast //мгновенно применяется
		}
}

